name: Run Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2
    
    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '14'
    
    - name: Install dependencies
      run: |
        npm install -g jasmine
        npm install  # Si tienes package.json con dependencias
    
    - name: Run tests
      run: |
        jasmine
        # O si quieres ser explícito:
        # jasmine --config=spec/support/jasmine.json
